name=ADS8688a
version=1.0.0
author=Inverated <thefakeonexd@gmail.com>
maintainer=Inverated <thefakeonexd@gmail.com>
sentence=ADS8688a Arduino Library
paragraph=Adapted ADS8688a library from siteswapjuggler for ESP32
category=Device Control
url=https://github.com/Inverated/ADS8688-Library
architectures=*
includes=ADS8688.h